// Feather disable all

#macro INTERFACE_COLOR_RED_TEXT     #ff5555
#macro INTERFACE_COLOR_ORANGE_TEXT  #ff8866
#macro INTERFACE_COLOR_GREEN_TEXT   #55ff55

#macro INTERACE_DEFAULT_PATH_SAVEDATA  game_save_id